import { Navigation } from '../components/Navigation';
import { Footer } from '../components/Footer';

export function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <Navigation />
      
      <main className="container mx-auto px-4 pt-24 pb-12">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold mb-8">Terms and Conditions</h1>
          <p className="text-muted-foreground mb-8">Last updated: 01/12/2025</p>

          <div className="prose prose-gray dark:prose-invert max-w-none space-y-8">
            <section>
              <h2 className="text-2xl font-semibold mb-4">1. Agreement to Terms</h2>
              <p className="text-muted-foreground">
                By accessing or using GeoScale, you agree to be bound by these Terms and Conditions. If you disagree with any part of these terms, you do not have permission to access the service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
              <p className="text-muted-foreground">
                GeoScale is a software-as-a-service platform that helps businesses create geo-targeted landing pages using AI-generated content. The service includes content generation, WordPress publishing integration, and search ranking tracking features.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">3. User Accounts</h2>
              <p className="text-muted-foreground mb-4">
                When you create an account with us, you must provide accurate, complete, and current information. You are responsible for:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Maintaining the confidentiality of your account credentials</li>
                <li>All activities that occur under your account</li>
                <li>Notifying us immediately of any unauthorised use</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">4. Subscription and Payment</h2>
              <p className="text-muted-foreground mb-4">
                <strong>Free Trial:</strong> New users receive a 7-day free trial with full access to features. No credit card is required to start the trial.
              </p>
              <p className="text-muted-foreground mb-4">
                <strong>Billing:</strong> Paid subscriptions are billed monthly or as a one-off payment depending on the plan selected. Payments are processed securely through Stripe.
              </p>
              <p className="text-muted-foreground mb-4">
                <strong>Cancellation:</strong> You may cancel your subscription at any time. Access will continue until the end of your current billing period.
              </p>
              <p className="text-muted-foreground">
                <strong>Refunds:</strong> Refunds are handled on a case-by-case basis. Please contact <a href="mailto:support@geoscale.app" className="text-[var(--brand-dark)] hover:underline">support@geoscale.app</a> for refund requests.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">5. Acceptable Use</h2>
              <p className="text-muted-foreground mb-4">You agree not to use GeoScale to:</p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Generate content that is illegal, harmful, or violates any laws</li>
                <li>Create spam or misleading content</li>
                <li>Infringe on intellectual property rights of others</li>
                <li>Attempt to gain unauthorised access to our systems</li>
                <li>Interfere with or disrupt the service</li>
                <li>Resell or redistribute the service without permission</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">6. Content Ownership</h2>
              <p className="text-muted-foreground mb-4">
                <strong>Your Content:</strong> You retain ownership of all content you input into GeoScale, including business information, locations, and keywords.
              </p>
              <p className="text-muted-foreground mb-4">
                <strong>Generated Content:</strong> Content generated by GeoScale using AI is provided for your use. You are granted a licence to use, modify, and publish this content on your websites.
              </p>
              <p className="text-muted-foreground">
                <strong>Responsibility:</strong> You are responsible for reviewing and editing generated content before publication. We do not guarantee the accuracy, completeness, or suitability of AI-generated content.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">7. WordPress Integration</h2>
              <p className="text-muted-foreground">
                By connecting your WordPress site to GeoScale, you authorise us to publish content to your site using the credentials you provide. You are responsible for ensuring you have the right to publish content to any connected websites.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">8. Service Availability</h2>
              <p className="text-muted-foreground">
                We strive to maintain high availability but do not guarantee uninterrupted access to the service. We may perform maintenance or updates that temporarily affect availability. We are not liable for any downtime or service interruptions.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">9. Limitation of Liability</h2>
              <p className="text-muted-foreground">
                To the maximum extent permitted by law, GeoScale shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities, arising from your use of the service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">10. Disclaimer of Warranties</h2>
              <p className="text-muted-foreground">
                The service is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that the service will meet your requirements, be error-free, or that any defects will be corrected.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">11. Indemnification</h2>
              <p className="text-muted-foreground">
                You agree to indemnify and hold harmless GeoScale and its officers, directors, employees, and agents from any claims, damages, losses, or expenses arising from your use of the service or violation of these terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">12. Termination</h2>
              <p className="text-muted-foreground">
                We may terminate or suspend your account immediately, without prior notice, for any breach of these Terms. Upon termination, your right to use the service will cease immediately.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">13. Changes to Terms</h2>
              <p className="text-muted-foreground">
                We reserve the right to modify these terms at any time. We will provide notice of significant changes by posting the new terms on this page. Your continued use of the service after changes constitutes acceptance of the new terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">14. Governing Law</h2>
              <p className="text-muted-foreground">
                These terms shall be governed by and construed in accordance with the laws of England and Wales, without regard to its conflict of law provisions.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">15. Contact Us</h2>
              <p className="text-muted-foreground">
                If you have any questions about these Terms and Conditions, please contact us at:<br />
                <a href="mailto:support@geoscale.app" className="text-[var(--brand-dark)] hover:underline">support@geoscale.app</a>
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
